sonar.sources=user-service/src/main/kotlin,ticket-service/src/main/kotlin,event-service/src/main/kotlin
sonar.tests=user-service/src/test/kotlin,ticket-service/src/test/kotlin,event-service/src/test/kotlin
sonar.sourceEncoding=UTF-8

sonar.cpd.exclusions=\
  **/domain/OutboxEvent.kt,\
  **/config/JpaLiquibaseDependencyPostProcessor.kt,\
  **/config/KafkaConfig.kt,\
  **/messaging/UserDeletedConsumer.kt,\
  **/messaging/OutboxPublisher.kt,\
  **/client/UserKeyClient.kt,\
  event-service/src/main/kotlin/com/ems/eventservice/crypto/EventCryptoService.kt,\
  ticket-service/src/main/kotlin/com/ems/ticketservice/crypto/TicketCryptoService.kt,\
  **/exception/GlobalExceptionHandler.kt
