#!/usr/bin/env bash
set -euo pipefail

GATEWAY_URL="${GATEWAY_URL:-http://localhost:8083}"
KEYCLOAK_URL="${KEYCLOAK_URL:-http://localhost:8088}"
KEYCLOAK_REALM="${KEYCLOAK_REALM:-ems}"
KEYCLOAK_CLIENT_ID="${KEYCLOAK_CLIENT_ID:-ems-api-gateway}"
KEYCLOAK_ADMIN_USER="${KEYCLOAK_ADMIN_USER:-admin}"
KEYCLOAK_ADMIN_PASSWORD="${KEYCLOAK_ADMIN_PASSWORD:?KEYCLOAK_ADMIN_PASSWORD must be set}"
E2E_USER_PASSWORD="${E2E_USER_PASSWORD:?E2E_USER_PASSWORD must be set}"

require_command() {
  command -v "$1" >/dev/null 2>&1 || {
    printf 'Missing required command: %s\n' "$1" >&2
    exit 1
  }
}

json_post() {
  local url="$1"
  local body="$2"
  local token="${3:-}"
  if [[ -n "$token" ]]; then
    curl -fsS -X POST "$url" \
      -H "Authorization: Bearer $token" \
      -H "Content-Type: application/json" \
      -d "$body"
  else
    curl -fsS -X POST "$url" \
      -H "Content-Type: application/json" \
      -d "$body"
  fi
}

get_token() {
  local username="$1"
  local password="$2"

  curl -fsS \
    -d "client_id=${KEYCLOAK_CLIENT_ID}" \
    -d "username=${username}" \
    -d "password=${password}" \
    -d "grant_type=password" \
    "${KEYCLOAK_URL}/realms/${KEYCLOAK_REALM}/protocol/openid-connect/token" |
    jq -r '.access_token'
}

get_admin_token() {
  curl -fsS \
    -d "client_id=admin-cli" \
    -d "username=${KEYCLOAK_ADMIN_USER}" \
    -d "password=${KEYCLOAK_ADMIN_PASSWORD}" \
    -d "grant_type=password" \
    "${KEYCLOAK_URL}/realms/master/protocol/openid-connect/token" |
    jq -r '.access_token'
}

assign_realm_roles() {
  local admin_token="$1"
  local user_id="$2"
  shift 2

  local roles_json="[]"
  local role
  for role in "$@"; do
    local role_json
    role_json="$(curl -fsS \
      -H "Authorization: Bearer ${admin_token}" \
      "${KEYCLOAK_URL}/admin/realms/${KEYCLOAK_REALM}/roles/${role}")"
    roles_json="$(jq --argjson role "$role_json" '. + [$role]' <<<"$roles_json")"
  done

  curl -fsS -X POST \
    -H "Authorization: Bearer ${admin_token}" \
    -H "Content-Type: application/json" \
    -d "$roles_json" \
    "${KEYCLOAK_URL}/admin/realms/${KEYCLOAK_REALM}/users/${user_id}/role-mappings/realm" >/dev/null
}

create_keycloak_user() {
  local admin_token="$1"
  local user_id="$2"
  local email="$3"
  shift 3

  curl -fsS -X POST \
    -H "Authorization: Bearer ${admin_token}" \
    -H "Content-Type: application/json" \
    -d "{
      \"id\": \"${user_id}\",
      \"username\": \"${email}\",
      \"email\": \"${email}\",
      \"enabled\": true,
      \"emailVerified\": true,
      \"credentials\": [
        {
          \"type\": \"password\",
          \"value\": \"${E2E_USER_PASSWORD}\",
          \"temporary\": false
        }
      ]
    }" \
    "${KEYCLOAK_URL}/admin/realms/${KEYCLOAK_REALM}/users" >/dev/null || true

  assign_realm_roles "$admin_token" "$user_id" "$@"
}

wait_for_json() {
  local description="$1"
  local command="$2"
  local attempts="${3:-30}"
  local delay="${4:-2}"

  local output=""
  for _ in $(seq 1 "$attempts"); do
    if output="$(eval "$command" 2>/dev/null)" && [[ -n "$output" ]]; then
      printf '%s\n' "$output"
      return 0
    fi
    sleep "$delay"
  done

  printf 'Timed out waiting for %s\n' "$description" >&2
  return 1
}

require_command curl
require_command jq

run_id="$(date +%s)"
organizer_email="organizer-${run_id}@ems.local"
buyer_email="buyer-${run_id}@ems.local"

printf 'Creating user-service organizer and buyer records...\n'
organizer_response="$(json_post "${GATEWAY_URL}/api/v1/users" "{\"email\":\"${organizer_email}\"}")"
buyer_response="$(json_post "${GATEWAY_URL}/api/v1/users" "{\"email\":\"${buyer_email}\"}")"
organizer_id="$(jq -r '.id' <<<"$organizer_response")"
buyer_id="$(jq -r '.id' <<<"$buyer_response")"

printf 'Creating matching Keycloak organizer identity...\n'
admin_token="$(get_admin_token)"
create_keycloak_user "$admin_token" "$organizer_id" "$organizer_email" USER ORGANIZER ADMIN
organizer_token="$(get_token "$organizer_email" "$E2E_USER_PASSWORD")"

starts_at="$(date -u -d '+30 days' '+%Y-%m-%dT%H:%M:%S')"
printf 'Creating event through api-gateway as organizer...\n'
event_response="$(json_post "${GATEWAY_URL}/api/v1/organizers/me/events" "{
  \"title\": \"E2E Purchase Flow ${run_id}\",
  \"description\": \"Generated by e2e-purchase-flow.sh\",
  \"location\": \"Warsaw\",
  \"startsAt\": \"${starts_at}\",
  \"capacity\": 50,
  \"organizerNote\": \"private organizer note\"
}" "$organizer_token")"
event_id="$(jq -r '.id' <<<"$event_response")"

printf 'Reserving ticket...\n'
ticket_response="$(json_post "${GATEWAY_URL}/api/v1/tickets" "{
  \"userId\": \"${buyer_id}\",
  \"eventId\": \"${event_id}\",
  \"holderName\": \"E2E Buyer\",
  \"seatCode\": \"A-${run_id}\",
  \"amount\": 49.99,
  \"currency\": \"USD\"
}" "$organizer_token")"
ticket_id="$(jq -r '.id' <<<"$ticket_response")"

printf 'Waiting for payment created by saga choreography...\n'
payment_response="$(wait_for_json "payment for ticket ${ticket_id}" \
  "curl -fsS -H 'Authorization: Bearer ${organizer_token}' '${GATEWAY_URL}/api/v1/payments/by-ticket/${ticket_id}'")"
payment_id="$(jq -r '.id' <<<"$payment_response")"

printf 'Capturing payment...\n'
json_post "${GATEWAY_URL}/api/v1/payments/${payment_id}/capture" "{}" "$organizer_token" >/dev/null

printf 'Waiting for active ticket and receipt...\n'
wait_for_json "active ticket ${ticket_id}" \
  "curl -fsS -H 'Authorization: Bearer ${organizer_token}' '${GATEWAY_URL}/api/v1/tickets/${ticket_id}' | jq -e 'select(.status == \"ACTIVE\")'" >/dev/null
receipt_response="$(wait_for_json "receipt for payment ${payment_id}" \
  "curl -fsS -H 'Authorization: Bearer ${organizer_token}' '${GATEWAY_URL}/api/v1/payments/${payment_id}/receipt'")"

printf 'Waiting for payment notification...\n'
notification_response="$(wait_for_json "notification for user ${buyer_id}" \
  "curl -fsS -H 'Authorization: Bearer ${organizer_token}' '${GATEWAY_URL}/api/v1/notifications/users/${buyer_id}' | jq -e 'map(select(.sourceEventType == \"PaymentSucceeded\")) | select(length > 0)'")"

printf 'E2E purchase flow completed successfully.\n'
jq -n \
  --arg organizerId "$organizer_id" \
  --arg buyerId "$buyer_id" \
  --arg eventId "$event_id" \
  --arg ticketId "$ticket_id" \
  --arg paymentId "$payment_id" \
  --arg receiptUrl "$(jq -r '.receiptUrl' <<<"$receipt_response")" \
  --arg notificationId "$(jq -r '.[0].id' <<<"$notification_response")" \
  '{
    organizerId: $organizerId,
    buyerId: $buyerId,
    eventId: $eventId,
    ticketId: $ticketId,
    paymentId: $paymentId,
    receiptUrl: $receiptUrl,
    notificationId: $notificationId
  }'
